// src/app/spinner/spinner.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-spinner',
  template: `<svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="100%"
    height="100%"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    fill="currentcolor"
    class="default-spinner"
  >
    <g transform="rotate(0 50 50)">
      <rect x="42.5" y="22.5" rx="7.5" ry="7.5" width="15" height="15">
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.8s"
          repeatCount="indefinite"
        ></animate>
      </rect>
    </g>
    <g transform="rotate(72 50 50)">
      <rect x="42.5" y="22.5" rx="7.5" ry="7.5" width="15" height="15">
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.6s"
          repeatCount="indefinite"
        ></animate>
      </rect>
    </g>
    <g transform="rotate(144 50 50)">
      <rect x="42.5" y="22.5" rx="7.5" ry="7.5" width="15" height="15">
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.4s"
          repeatCount="indefinite"
        ></animate>
      </rect>
    </g>
    <g transform="rotate(216 50 50)">
      <rect x="42.5" y="22.5" rx="7.5" ry="7.5" width="15" height="15">
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.2s"
          repeatCount="indefinite"
        ></animate>
      </rect>
    </g>
    <g transform="rotate(288 50 50)">
      <rect x="42.5" y="22.5" rx="7.5" ry="7.5" width="15" height="15">
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="0s"
          repeatCount="indefinite"
        ></animate>
      </rect>
    </g>
  </svg>`,
})
export class SpinnerComponent {}

// src/components/Spinner/Spinner.tsx
export function Spinner({ title }: { title: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="currentcolor"
      width="100%"
      height="100%"
      preserveAspectRatio="xMidYMid"
      viewBox="0 0 100 100"
    >
      <title>{title}</title>
      <rect width="0.738em" height="0.738em" x="42.5" y="22.5" rx="7.5" ry="7.5">
        <animate
          attributeName="opacity"
          begin="-0.8s"
          dur="1s"
          keyTimes="0;1"
          repeatCount="indefinite"
          values="1;0"
        />
      </rect>
      <rect
        width="0.738em"
        height="0.738em"
        x="42.5"
        y="22.5"
        rx="7.5"
        ry="7.5"
        transform="rotate(72 50 50)"
      >
        <animate
          attributeName="opacity"
          begin="-0.6s"
          dur="1s"
          keyTimes="0;1"
          repeatCount="indefinite"
          values="1;0"
        />
      </rect>
      <rect
        width="0.738em"
        height="0.738em"
        x="42.5"
        y="22.5"
        rx="7.5"
        ry="7.5"
        transform="rotate(144 50 50)"
      >
        <animate
          attributeName="opacity"
          begin="-0.4s"
          dur="1s"
          keyTimes="0;1"
          repeatCount="indefinite"
          values="1;0"
        />
      </rect>
      <rect
        width="0.738em"
        height="0.738em"
        x="42.5"
        y="22.5"
        rx="7.5"
        ry="7.5"
        transform="rotate(216 50 50)"
      >
        <animate
          attributeName="opacity"
          begin="-0.2s"
          dur="1s"
          keyTimes="0;1"
          repeatCount="indefinite"
          values="1;0"
        />
      </rect>
      <rect
        width="0.738em"
        height="0.738em"
        x="42.5"
        y="22.5"
        rx="7.5"
        ry="7.5"
        transform="rotate(288 50 50)"
      >
        <animate
          attributeName="opacity"
          begin="0s"
          dur="1s"
          keyTimes="0;1"
          repeatCount="indefinite"
          values="1;0"
        />
      </rect>
    </svg>
  );
}
Spinner.defaultProps = {
  title: 'Loading...',
};
